name: Lint Commit Messages

on:
  # Only run on pull requests and hotfix branches to avoid conflicts
  push:
    branches:
      - "hotfix/*"
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
